import test from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {create,act} from 'react-test-renderer';
import {build} from 'esbuild';
import {mkdtemp,rm} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
const dir=path.dirname(fileURLToPath(import.meta.url));
const temp=await mkdtemp(path.join(dir,'.search-screen-test-'));
await build({entryPoints:[path.join(dir,'catalog-app.js')],bundle:true,packages:'external',platform:'node',format:'esm',outfile:path.join(temp,'app.mjs'),logLevel:'silent'});
const {default:App}=await import(pathToFileURL(path.join(temp,'app.mjs')));
await rm(temp,{recursive:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const text=node=>typeof node==='string'||typeof node==='number'?String(node):(node?.children||[]).map(text).join('');
test('The actual search screen opens URL results and preserves the query while revealing filtered Target matches',async()=>{
 globalThis.window={location:{search:'?q=sponge%20cloth'},localStorage:{getItem:()=>null},setInterval:()=>1,clearInterval(){},setTimeout:fn=>{fn();return 2;},clearTimeout(){}};
 globalThis.document={getElementById:()=>({scrollIntoView(){}})};
 let screen;
 const click=async label=>{await act(async()=>{const button=screen.root.findAllByType('button').find(b=>text(b)===label);assert.ok(button,label);button.props.onClick();});};
 const search=()=>screen.root.findByProps({'aria-label':'Search products'});
 const cards=()=>screen.root.findAllByProps({className:'product-card'});
 try {
  await act(async()=>{screen=create(React.createElement(App));});
  assert.equal(search().props.value,'sponge cloth');
  assert.equal(cards().length,13);
  const needsButton=screen.root.findAllByType('button').find(b=>text(b).startsWith('Needs Target check ·'));
  await act(async()=>needsButton.props.onClick());
  assert.equal(search().props.value,'sponge cloth');
  assert.equal(cards().length,8);
  assert.match(text(screen.toJSON()),/5 are hidden by your current filters/);
  await act(async()=>search().props.onChange({target:{value:'Everspring sponge cloth'}}));
  assert.equal(cards().length,0);
  await click('Show all 1 matches');
  assert.equal(search().props.value,'Everspring sponge cloth');
  assert.equal(cards().length,1);
  await act(async()=>search().props.onChange({target:{value:'Swedish dishcloth'}}));
  assert.equal(cards().length,12);
  assert.ok(cards().every(card=>!text(card).includes('Libman')));
  await click('Viral history · 20');
  assert.equal(cards().length,0);
  await click('Show all 20 history items');
  assert.equal(search().props.value,'');
  assert.equal(cards().length,20);
  assert.equal(screen.root.findAllByProps({className:'viral-history-note'}).length,20);
  assert.match(text(cards()[0]),/Original signal date: Not recorded/);
  await click('Fresh viral signals · 0');
  assert.equal(cards().length,0);
  await click('View viral history (20)');
  assert.equal(cards().length,20);
  await act(async()=>screen.unmount());
  window.location.search='?view=history';
  await act(async()=>{screen=create(React.createElement(App));});
  assert.equal(cards().length,20);
  await click('Brazilian Bliss Mop Soap');
  assert.equal(screen.root.findAllByProps({className:'viral-history-detail'}).length,1);
  assert.match(text(screen.root.findByProps({className:'viral-history-detail'})),/Recorded claim: 2.3K sold on TikTok Shop/);
  await act(async()=>screen.root.findByProps({'aria-label':'Close decision brief'}).props.onClick());
  await click('Target should try · 0');
  const recommendations=screen.root.findByProps({'aria-label':'Ranked Target recommendations'});
  assert.match(text(recommendations),/No confirmed missing items yet/);
  assert.match(text(recommendations),/Market-supported investigations/);
  assert.match(text(recommendations),/not ranked against one another/);
  assert.equal(screen.root.findAllByProps({className:'recommendation-row'}).length,3);
  await act(async()=>screen.unmount());
  window.location.search='?view=recommendations';
  await act(async()=>{screen=create(React.createElement(App));});
  assert.equal(screen.root.findAllByProps({'aria-label':'Ranked Target recommendations'}).length,1);
 } finally {
  if(screen)await act(async()=>screen.unmount());
  delete globalThis.window;
  delete globalThis.document;
 }
});
