import {build} from 'esbuild';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const dir=path.dirname(fileURLToPath(import.meta.url));
const root=path.dirname(dir);
await mkdir(path.join(root,'assets'),{recursive:true});
await build({entryPoints:[path.join(dir,'catalog-app.js')],bundle:true,platform:'node',format:'esm',outfile:path.join(dir,'.render.mjs'),packages:'external',loader:{'.jsx':'jsx'},logLevel:'warning'});
const {default:App,catalog,categories}=await import('./.render.mjs?build='+Date.now());
if(catalog.length<1900||new Set(catalog.map(p=>p.id)).size!==catalog.length||categories.length!==27)throw Error('Catalog count/category regression');
const React=await import('react');const {renderToString}=await import('react-dom/server');
const html=renderToString(React.createElement(App));
const bundle=await build({entryPoints:[path.join(dir,'client.jsx')],bundle:true,minify:true,charset:'utf8',format:'esm',write:false,define:{'process.env.NODE_ENV':'"production"'},logLevel:'warning'});
const js=bundle.outputFiles[0].contents;const hash=createHash('sha256').update(js).digest('hex').slice(0,12);
await writeFile(path.join(root,'assets',`app-${hash}.js`),js);
const css=await readFile(path.join(dir,'styles.css'),'utf8')+'\n'+await readFile(path.join(dir,'restored.css'),'utf8');const cssHash=createHash('sha256').update(css).digest('hex').slice(0,12);
await writeFile(path.join(root,'assets',`style-${cssHash}.css`),css);
await writeFile(path.join(root,'index.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CleanTrend Opportunity Hub</title><meta name="description" content="Explore cleaning products, investigate Target opportunities and compare your shortlist."><link rel="icon" href="/cleantrend-opportunity-hub/favicon.svg"><link rel="stylesheet" href="/cleantrend-opportunity-hub/assets/style-${cssHash}.css"></head><body><div id="app">${html}</div><script type="module" src="/cleantrend-opportunity-hub/assets/app-${hash}.js"></script></body></html>`);
console.log(JSON.stringify({products:catalog.length,categories:categories.length,javascript:`assets/app-${hash}.js`,stylesheet:`assets/style-${cssHash}.css`,htmlBytes:html.length}));
