import test from 'node:test';
import assert from 'node:assert/strict';
import React from 'react';
import {create,act} from 'react-test-renderer';
import {build} from 'esbuild';
import {mkdtemp,rm} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import path from 'node:path';
const dir=path.dirname(fileURLToPath(import.meta.url));
const temp=await mkdtemp(path.join(dir,'.checkout-test-'));
await build({entryPoints:[path.join(dir,'decision-ui.jsx')],bundle:true,packages:'external',platform:'node',format:'esm',outfile:path.join(temp,'ui.mjs'),logLevel:'silent'});
const {CheckoutRecords}=await import(pathToFileURL(path.join(temp,'ui.mjs')));
await rm(temp,{recursive:true});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const key='isolated-checkout-test';
const first={id:'test-a',merchantName:'Synthetic A',createdAt:'2026-09-01T00:00:00Z',productNames:['Legacy test product'],targetRetailPrice:'9.99'};
const second={id:'test-b',merchantName:'Synthetic B',createdAt:'2026-09-02T00:00:00Z',items:[{productId:'test-item',productName:'New-format test product'}]};
test('Checkout deletion, undo, clear-all and reload operate on saved records without email',async()=>{
 const data=new Map([[key,JSON.stringify([first,second])]]);
 let fail=false;
 globalThis.window={localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>{if(fail)throw Error('Storage blocked');data.set(k,v)}}};
 let renderer;
 function Harness(){const [records,setRecords]=React.useState(()=>JSON.parse(window.localStorage.getItem(key)));return React.createElement(CheckoutRecords,{records,onChange:setRecords,storageKey:key,imagePath:p=>p});}
 const mount=async()=>{await act(async()=>{renderer=create(React.createElement(Harness));});};
 const click=async label=>{await act(async()=>{renderer.root.findAllByType('button').find(b=>b.props['aria-label']===label||b.props.children===label).props.onClick();});};
 const saved=()=>JSON.parse(data.get(key));
 await mount();
 await click('Delete record 1 for Synthetic A');
 assert.deepEqual(saved().map(r=>r.id),['test-b']);
 await click('Undo');
 assert.deepEqual(saved().map(r=>r.id).sort(),['test-a','test-b']);
 await click('Delete record 1 for Synthetic A');
 await act(async()=>renderer.unmount());
 await mount();
 assert.match(JSON.stringify(renderer.toJSON()),/Synthetic B/);
 assert.doesNotMatch(JSON.stringify(renderer.toJSON()),/Synthetic A/);
 await click('Clear all records');
 assert.deepEqual(saved(),[]);
 assert.match(JSON.stringify(renderer.toJSON()),/No saved checkout records/);
 await click('Undo');
 assert.deepEqual(saved().map(r=>r.id),['test-b']);
 fail=true;
 await click('Clear all records');
 assert.deepEqual(saved().map(r=>r.id),['test-b']);
 assert.match(JSON.stringify(renderer.toJSON()),/Could not update saved records/);
 await act(async()=>renderer.unmount());
 delete globalThis.window;
});
