import React from 'react';
import {assess,offers,isFreshViral,trendLabel} from './logic.js';
import refresh from './refresh.json';

export function AssessmentGuide(){return <details className="assessment-guide"><summary>How to read an opportunity · four simple checks</summary><p><b>We use evidence checks, not an unexplained score out of 100.</b> Check Target assortment, shopper demand, price and supplier feasibility. A product is ready to propose for a test only when all four are supported.</p><div className="guide-grid"><article><b>Potential Target gap</b><p>A lead to investigate. A missing item in this partial directory does not prove Target has a gap.</p></article><article><b>Target alternatives to check</b><p>Related products are recorded. Look for a useful benefit, pack or price difference.</p></article><article><b>Not verified</b><p>There is not enough evidence yet. Open the item to see the next check.</p></article></div><p>A recorded Target listing is a benchmark. Older numeric scores are retained only in history and do not decide the recommendation.</p></details>}
export function RefreshNotice(){return <details className="refresh-notice"><summary>{refresh.schedule} · {refresh.lastSuccessfulCatalogRefresh ? `Last completed refresh: ${refresh.lastSuccessfulCatalogRefresh}` : 'First catalog refresh pending'}</summary><p>{refresh.notes}</p><p>{refresh.coverage}</p><p>Fresh viral signals require a dated source and a recent signal period. They expire after seven days without renewed evidence. A newly visited old article or cumulative sales total alone does not establish current viral growth.</p><p>Signal audit: {refresh.lastSignalAudit}. Listing dates remain the dates actually checked.</p></details>}
export function SignalTabs({products,active,onChange}){const opportunities=products.filter(p=>assess(p,products).tone==='potential').length;const fresh=products.filter(p=>isFreshViral(p)).length;const history=products.filter(p=>p.trend==='Viral'&&!isFreshViral(p)).length;return <div className="signal-tabs" aria-label="Product signal filters"><button className={active==='priority'?'active':''} onClick={()=>onChange('priority')}>Target opportunities · {opportunities}</button><button className={active==='all'?'active':''} onClick={()=>onChange('all')}>All products · {products.length.toLocaleString()}</button><button className={active==='viral'?'active':''} onClick={()=>onChange('viral')}>Fresh viral signals · {fresh}</button><button className={active==='history'?'active':''} onClick={()=>onChange('history')}>Historical signals · {history}</button>{active==='viral'&&!fresh&&<p>No current viral signals have sufficient dated evidence. Historical products are still available in the catalog.</p>}</div>}
export function CardDecision({product,catalog}){const d=assess(product,catalog);return <div className={`card-decision ${d.tone}`}><span className="decision-label">Target opportunity</span><strong>{d.status}</strong><p>{d.tone==='potential'?d.reason:d.status==='Target listing recorded'?'Use as a benchmark; a Target offer is recorded.':d.tone==='benchmark'?'Related Target products are recorded. Check the difference.':'We need a live Target comparison to decide.'}</p><small>{d.checked}/4 evidence checks supported</small></div>}
export function ItemDecision({product:p,catalog}){const d=assess(p,catalog);return <section className={`item-decision ${d.tone}`}><span className="eyebrow">Is it whitespace for Target?</span><h3>{d.status}</h3><p>{d.reason}</p><div className="next-action"><b>Next action</b><p>{d.next}</p></div>{d.similar.length>0&&<div className="target-comparators"><b>Suggested Target comparisons</b>{d.similar.map(q=>{const o=offers(q).find(x=>x.retailer==='Target');return <a key={q.id} href={o.link} target="_blank" rel="noreferrer">{q.brand} {q.name} · {o.priceLabel||'Price to check'} ↗</a>})}<small>Related category/format only. Confirm equivalent function, seller and pack at the source.</small></div>}<h4>{d.checked}/4 evidence checks supported</h4><div className="evidence-grid">{d.gates.map(g=><article key={g.label}><b>{g.ok?'✓':'○'} {g.label}</b><p>{g.detail}</p></article>)}</div><p className="decision-conclusion"><b>{d.ready?'Propose a merchant test for review.':'Research stage — not ready for a launch decision.'}</b></p><p><b>Recorded trend:</b> {trendLabel(p)}. {isFreshViral(p)?p.trendEvidence.summary:'Recheck present demand before using an older sales or social signal.'}</p></section>}
export function ComparisonDirection({items,catalog}){
 const rows=items.map(p=>({p,d:assess(p,catalog)}));const groups=[...new Set(items.map(p=>p.category))];const ready=rows.filter(x=>x.d.ready);const ranked=[...rows].sort((a,b)=>b.d.checked-a.d.checked);const top=ranked[0];const tied=top?ranked.filter(x=>x.d.checked===top.d.checked):[];
 return <section className="comparison-direction"><h3>Merchant direction</h3><p><b>{ready.length?`${ready.length} item(s) have evidence to propose a test.`:'No selection is ready for a test decision yet.'}</b> {groups.length>1?`These products span ${groups.length} categories. Assess each category separately; a cheaper product in another category is not better value.`:'These products share a category. Compare function and normalized pack cost before choosing one.'}</p><div className="direction-summary"><article><b>What to do first</b><p>{tied.length===1?`Review ${top.p.brand} ${top.p.name} first: it has ${top.d.checked}/4 evidence checks supported. This is research readiness, not a quality ranking.`:`${tied.length} items tie on documented evidence. There is no evidence-based winner yet; resolve the missing Target and demand checks below.`}</p></article><article><b>How to make the decision</b><p>Advance a product only if it adds a useful guest benefit or better comparable value, has current demand evidence, and meets your retail, margin and supplier requirements.</p></article></div><div className="direction-table-wrap"><table className="direction-table"><thead><tr><th>Product</th><th>Target opportunity</th><th>Evidence</th><th>Specific next step</th></tr></thead><tbody>{rows.map(({p,d})=><tr key={p.id}><th>{p.brand}<br/>{p.name}<small>{p.category}</small></th><td><b>{d.status}</b><p>{d.reason}</p></td><td>{d.checked}/4 checks<p>{d.gates.filter(g=>!g.ok).map(g=>g.label).join(', ')||'All four checks supported'}{d.checked<4?' still needed.':''}</p></td><td>{d.next}</td></tr>)}</tbody></table></div><p className="comparison-footnote">Use the detailed comparison below for pack-adjusted prices and recorded reviews. Different currencies, functions and pack units are not directly ranked. Supplier cost and Target margin are unknown until a quote is recorded.</p></section>
}
