import React from 'react';
import {assess,offers,isFreshViral,trendLabel} from './logic.js';
import refresh from './refresh.json';

export function AssessmentGuide(){return <details className="assessment-guide"><summary>What counts as Target whitespace?</summary><p><b>Only products verified as not currently carried by Target.</b> The review must check the exact product, equivalents and Target Plus. A missing record in this directory or a temporarily sold-out item does not qualify.</p><div className="guide-grid"><article><b>Verified Target whitespace</b><p>A documented Target absence check within the past 24 hours. The check date and sources appear on the item.</p></article><article><b>Target listing recorded</b><p>Excluded from whitespace. Keep these items for comparison.</p></article><article><b>Needs Target check</b><p>Not counted as whitespace until the current assortment has been checked.</p></article></div><p>The four checks cover Target absence, shopper demand, price and supplier feasibility. All four must be supported before proposing a whitespace test.</p></details>}
export function RefreshNotice(){return <details className="refresh-notice"><summary>{refresh.schedule} · {refresh.lastSuccessfulCatalogRefresh ? `Last completed refresh: ${refresh.lastSuccessfulCatalogRefresh}` : 'First catalog refresh pending'}</summary><p>{refresh.notes}</p><p>{refresh.coverage}</p><p>Fresh viral signals require a dated source and a recent signal period. They expire after seven days without renewed evidence. A newly visited old article or cumulative sales total alone does not establish current viral growth.</p><p>Signal audit: {refresh.lastSignalAudit}. Listing dates remain the dates actually checked.</p></details>}
export function SignalTabs({products,active,onChange}){const opportunities=products.filter(p=>assess(p,products).isWhitespace).length;const pending=products.filter(p=>assess(p,products).tone==='unknown').length;const fresh=products.filter(p=>isFreshViral(p)).length;const history=products.filter(p=>p.trend==='Viral'&&!isFreshViral(p)).length;return <div className="signal-tabs" aria-label="Product signal filters"><button className={active==='priority'?'active':''} onClick={()=>onChange('priority')}>Verified Target whitespace · {opportunities}</button><button className={active==='research'?'active':''} onClick={()=>onChange('research')}>Needs Target check · {pending.toLocaleString()}</button><button className={active==='all'?'active':''} onClick={()=>onChange('all')}>All products · {products.length.toLocaleString()}</button><button className={active==='viral'?'active':''} onClick={()=>onChange('viral')}>Fresh viral signals · {fresh}</button><button className={active==='history'?'active':''} onClick={()=>onChange('history')}>Historical signals · {history}</button>{active==='priority'&&<p>Only products verified as not currently carried by Target. Unknown products and recorded Target listings are excluded. Absence checks expire after 24 hours.</p>}{active==='research'&&<p>These products need a current Target check. They are not verified whitespace.</p>}{active==='viral'&&!fresh&&<p>No current viral signals have sufficient dated evidence. Historical products are still available in the catalog.</p>}</div>}
export function CardDecision({product,catalog}){const d=assess(product,catalog);return <div className={`card-decision ${d.tone}`}><span className="decision-label">Target whitespace</span><strong>{d.status}</strong><p>{d.isWhitespace?d.reason:d.tone==='benchmark'?'Excluded: a Target listing is recorded.':'Not counted as whitespace. A current Target absence check is needed.'}</p>{d.checkedAt&&<small>Checked {d.checkedAt}</small>}<small>{d.checked}/4 evidence checks supported</small></div>}
export function ItemDecision({product:p,catalog}){const d=assess(p,catalog);return <section className={`item-decision ${d.tone}`}><span className="eyebrow">Is it whitespace for Target?</span><h3>{d.status}</h3><p>{d.reason}</p>{d.checkedAt&&<div className="target-review-sources"><b>Target check: {d.checkedAt}</b>{d.sourceUrls.map((url,i)=><a key={url} href={url} target="_blank" rel="noreferrer">Target evidence {i+1} ↗</a>)}</div>}<div className="next-action"><b>Next action</b><p>{d.next}</p></div>{d.similar.length>0&&<div className="target-comparators"><b>Suggested Target comparisons</b>{d.similar.map(q=>{const o=offers(q).find(x=>x.retailer==='Target');return <a key={q.id} href={o.link} target="_blank" rel="noreferrer">{q.brand} {q.name} · {o.priceLabel||'Price to check'} ↗</a>})}<small>Related category/format only. Confirm equivalent function, seller and pack at the source.</small></div>}<h4>{d.checked}/4 evidence checks supported</h4><div className="evidence-grid">{d.gates.map(g=><article key={g.label}><b>{g.ok?'✓':'○'} {g.label}</b><p>{g.detail}</p></article>)}</div><p className="decision-conclusion"><b>{d.ready?'Propose a merchant test for review.':'Research stage — not ready for a launch decision.'}</b></p><p><b>Recorded trend:</b> {trendLabel(p)}. {isFreshViral(p)?p.trendEvidence.summary:'Recheck present demand before using an older sales or social signal.'}</p></section>}
export function ComparisonDirection({items,catalog}){
 const rows=items.map(p=>({p,d:assess(p,catalog)}));const groups=[...new Set(items.map(p=>p.category))];const ready=rows.filter(x=>x.d.ready);const ranked=[...rows].filter(x=>x.d.tone!=='benchmark').sort((a,b)=>Number(b.d.isWhitespace)-Number(a.d.isWhitespace)||b.d.checked-a.d.checked);const top=ranked[0];const tied=top?ranked.filter(x=>x.d.checked===top.d.checked):[];
 return <section className="comparison-direction"><h3>Merchant direction</h3><p><b>{ready.length?`${ready.length} item(s) have evidence to propose a test.`:'No selection is ready for a test decision yet.'}</b> {groups.length>1?`These products span ${groups.length} categories. Assess each category separately; a cheaper product in another category is not better value.`:'These products share a category. Compare function and normalized pack cost before choosing one.'}</p><div className="direction-summary"><article><b>What to do first</b><p>{!ranked.length?'All selected products have a Target listing recorded. Use them as benchmarks; none qualifies for a whitespace test.':tied.length===1?`Review ${top.p.brand} ${top.p.name} first: it has ${top.d.checked}/4 evidence checks supported. This is research readiness, not a quality ranking.`:`${tied.length} items tie on documented evidence. There is no evidence-based winner yet; resolve the missing Target and demand checks below.`}</p></article><article><b>How to make the decision</b><p>For a whitespace test, first verify that Target does not currently carry the product or an equivalent. Then confirm shopper demand, comparable value and supplier feasibility. Recorded Target products are benchmarks, not whitespace.</p></article></div><div className="direction-table-wrap"><table className="direction-table"><thead><tr><th>Product</th><th>Target opportunity</th><th>Evidence</th><th>Specific next step</th></tr></thead><tbody>{rows.map(({p,d})=><tr key={p.id}><th>{p.brand}<br/>{p.name}<small>{p.category}</small></th><td><b>{d.status}</b><p>{d.reason}</p></td><td>{d.checked}/4 checks<p>{d.gates.filter(g=>!g.ok).map(g=>g.label).join(', ')||'All four checks supported'}{d.checked<4?' still needed.':''}</p></td><td>{d.next}</td></tr>)}</tbody></table></div><p className="comparison-footnote">Use the detailed comparison below for pack-adjusted prices and recorded reviews. Different currencies, functions and pack units are not directly ranked. Supplier cost and Target margin are unknown until a quote is recorded.</p></section>
}

export function CheckoutRecords({records,onChange,storageKey,imagePath}) {
 const [removed,setRemoved]=React.useState([]);
 const [notice,setNotice]=React.useState('');
 function persist(next,message,undoItems){
  try { window.localStorage.setItem(storageKey,JSON.stringify(next)); onChange(next); setNotice(message); setRemoved(undoItems); }
  catch { setNotice('Could not update saved records. Check that browser storage is available and try again.'); }
 }
 function removeAt(index){persist(records.filter((_,i)=>i!==index),'Record deleted.',[records[index]]);}
 function undo(){const unique=removed.filter(r=>!records.some(x=>r.id?x.id===r.id:x===r));persist([...unique,...records],'Deletion undone.',[]);}
 return <details className="checkout-history" id="checkout-records"><summary>Checkout records ({records.length})</summary><div className="records-toolbar"><p>Saved in this browser. Delete removes the saved record from this device.</p>{records.length>0&&<button type="button" className="delete-record" onClick={()=>persist([],'All checkout records deleted.',records)}>Clear all records</button>}</div>{notice&&<div className="record-notice" role="status">{notice} {removed.length>0&&<button type="button" onClick={undo}>Undo</button>}</div>}{records.length?<div className="record-grid">{records.map((record,index)=><article className="checkout-record" key={record.id||index}><div className="record-heading"><span>{record.createdAt?new Date(record.createdAt).toLocaleDateString():'Saved record'}</span><strong>{record.merchantName||'Merchant selection'}</strong><button type="button" className="delete-record" aria-label={`Delete record ${index+1}${record.merchantName?' for '+record.merchantName:''}`} onClick={()=>removeAt(index)}>Delete record</button></div>{(record.items?.length?record.items:[{...record,productName:(record.productNames||[]).join(' · ')}]).map((item,i)=><section className="record-item" key={item.productId||i}><div className="record-item-product">{item.image&&<img src={imagePath(item.image)} alt={item.productName||'Selected product'}/>}<strong>{item.productName}</strong></div><dl><div><dt>Target retail</dt><dd>{item.targetRetailPrice||'—'}</dd></div><div><dt>Target PMU</dt><dd>{item.targetPmu||'—'}</dd></div><div><dt>Number of stores</dt><dd>{item.numberOfStores||'—'}</dd></div><div><dt>Potential launch</dt><dd>{item.potentialLaunchDate||'—'}</dd></div></dl>{item.comments&&<small>{item.comments}</small>}</section>)}</article>)}</div>:<div className="empty-records">No saved checkout records.</div>}</details>
}
