import test from 'node:test';
import assert from 'node:assert/strict';
import {isFreshViral,assess,DAY} from './logic.js';
const now=Date.parse('2026-09-14T12:00:00Z');
const item=(extra={})=>({id:'a',name:'New sponge',brand:'A',category:'Sponges',tags:[],...extra});
const review=(extra={})=>({status:'not-carried',currentlyCarried:false,equivalentCurrentlyCarried:false,temporarilyOutOfStock:false,reviewedBy:'Test reviewer',checkedAt:'2026-09-14T11:00:00Z',scope:'target-us',exactProductChecked:true,equivalentsChecked:true,targetPlusChecked:true,reason:'Synthetic absence review for this test only.',sourceUrls:['https://www.target.com/s?searchTerm=synthetic-test-product'],...extra});
function decision(p,peers=[]){return assess(p,[p,...peers],now);}
test('Viral status requires current evidence and rejects future dates',()=>{const p=item({trend:'Viral'});assert.equal(isFreshViral(p,now),false);p.trendEvidence={qualified:true,sourceUrl:'https://example.com/item',summary:'Dated velocity',observedAt:'2026-09-14',periodEnd:'2026-09-13'};assert.equal(isFreshViral(p,now),true);p.trendEvidence.periodEnd='2026-08-31';assert.equal(isFreshViral(p,now),false);p.trendEvidence.periodEnd='2026-10-01';assert.equal(isFreshViral(p,now),false)});
test('A missing format in a partially captured Target category is never whitespace',()=>{const p=item();const q=item({id:'b',name:'Cleaning cloth',retailer:'Target',channel:'Target'});const d=decision(p,[q]);assert.equal(d.status,'Needs Target check');assert.equal(d.isWhitespace,false);assert.equal(d.gates[0].ok,false);assert.equal(d.ready,false)});
test('Only a complete current absence check can qualify; old potential flags cannot',()=>{assert.equal(decision(item({targetAssessment:review()})).isWhitespace,true);for(const patch of [{status:'potential-gap'},{sourceUrls:['https://example.com/no-result']},{reviewedBy:''},{scope:'target-online-only'},{exactProductChecked:false},{equivalentsChecked:false},{targetPlusChecked:false},{equivalentCurrentlyCarried:true},{currentlyCarried:true},{temporarilyOutOfStock:true},{checkedAt:'2026-09-15T00:00:00Z'}]){assert.equal(decision(item({targetAssessment:review(patch)})).isWhitespace,false,JSON.stringify(patch))}});
test('A Target absence check expires at 24 hours, including a previously cached result',()=>{const p=item({targetAssessment:review({checkedAt:'2026-09-14T11:00:30Z'})}),cat=[p];const expires=Date.parse(p.targetAssessment.checkedAt)+DAY;assert.equal(assess(p,cat,expires-1).isWhitespace,true);assert.equal(assess(p,cat,expires).isWhitespace,false)});
test('Target and Target Plus listings veto whitespace, including out of stock items',()=>{for(const o of [{retailer:'Target',channel:'Target'},{retailer:'Target Plus',availabilityStatus:'Out of stock'},{retailer:'Marketplace seller',link:'https://www.target.com/p/example'}]){const p=item({availability:[o],targetAssessment:review()});assert.equal(decision(p).isWhitespace,false);assert.equal(decision(p).status,'Target listing recorded')}});
test('A prior Target listing needs a newer explicit delisting check, and fresh positive observations veto it',()=>{const p=item({availability:[{retailer:'Target',evidence:{checkedAt:'2026-09-11T09:00:00Z'}}],targetAssessment:review({previousListingResolved:true})});assert.equal(decision(p).isWhitespace,true);assert.equal(decision({...p,availability:[{retailer:'Target',evidence:{checkedAt:'2026-09-14T11:30:00Z'}}]}).isWhitespace,false)});
test('Related formats are comparisons and do not decide Target absence',()=>{const q=item({id:'b',name:'Sponge 2pk',brand:'B',retailer:'Target',link:'https://www.target.com/p/item'});const d=decision(item(),[q]);assert.equal(d.similar[0].id,'b');assert.equal(d.isWhitespace,false);assert.equal(d.status,'Needs Target check')});
test('Commercial evidence cannot make an unverified product ready for a whitespace test',()=>{const p=item({demandEvidence:{sourceUrl:'https://example.com/demand',summary:'Synthetic demand',checkedAt:'2026-09-14T11:00:00Z'},priceUsd:3,link:'https://example.com/product',evidence:{checkedAt:'2026-09-14T11:00:00Z'},feasibility:{approved:true,reviewedBy:'Test',sourceUrl:'https://example.com/quote',checkedAt:'2026-09-14T11:00:00Z'}});assert.equal(decision(p).checked,3);assert.equal(decision(p).ready,false);assert.equal(decision({...p,targetAssessment:review()}).ready,true)});
